{% set name = "sdl" %}
{% set version = "1.2.68" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/libsdl-org/sdl12-compat/archive/release-{{ version }}.tar.gz
    sha256: 63c6e4dcc1154299e6f363c872900be7f3dcb3e42b9f8f57e05442ec3d89d02d


build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja

  host:
    - sdl2
  run:
    - sdl2

test:
  commands:
    - test -f ${PREFIX}/include/SDL/SDL.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\SDL\\SDL.h exit 1  # [win]
    - pkg-config --exists --print-errors --debug sdl  # [not win]
    - pkg-config --validate --print-errors --debug sdl  # [not win]
  requires:
    - pkg-config

about:
  home: https://www.libsdl.org/index.php
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Simple DirectMedia Layer

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
    - ymontmarin
