schema_version: 1

context:
  name: sdl3
  version: "3.2.22"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/libsdl-org/SDL/releases/download/release-${{ version }}/SDL3-${{ version }}.tar.gz
  sha256: f29d00cbcee273c0a54f3f32f86bf5c595e8823a96b1d92a145aac40571ebfcc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libusb
    - libvulkan-loader
    - if: not win
      then: dbus
    - if: linux
      then:
        # 202505 - hmaarrfk 
        # jack seems like it was added as a holdover
        # and we aren't sure if any users need it in
        # their modern (2025) workflows
        # https://github.com/conda-forge/sdl-feedstock/pull/33#issuecomment-2851145783
        # It may also pull in AGPL code
        # https://github.com/conda-forge/jack-feedstock/pull/27
        # - jack
        - pulseaudio-client
        - wayland
        - libdrm
        - libudev
        - liburing
        - libunwind
        - libxkbcommon
        - libgl-devel
        - libegl-devel
        - xorg-libx11
        - xorg-libxext
        - xorg-libxfixes
        - xorg-libxcursor
        - if: x86_64
          then: xorg-libxscrnsaver
  run_exports:
    - ${{ pin_subpackage(name|lower, upper_bound='x') }}

tests:
  - package_contents:
      lib:
        - SDL3
      include:
        - SDL3/SDL.h
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --modversion ${{ name }}

about:
  summary: Low-level access to audio, keyboard, mouse, joystick, and graphics
  description: |
    Simple DirectMedia Layer (SDL for short) is a cross-platform library designed
    to make it easy to write multi-media software, such as games and emulators.
  license: Zlib
  license_file: LICENSE.txt
  homepage: https://www.libsdl.org/
  repository: https://github.com/libsdl-org/SDL
  documentation: https://wiki.libsdl.org/SDL3/FrontPage

extra:
  recipe-maintainers:
    - traversaro
    - ymontmarin
    - ManifoldFR
